version: "3"

services:
  #Mongodb service
  db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db:/common/db

  # Web service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "80:3001"
    depends_on:
      - db
    command: >
      sh -c "npm i &&
             npm start"
volumes:
  db: {}
